### ISSUE TITLE
DoxBox Explorer complains about not having drivers

### ISSUE THREAD

**Issue by ConorIA** [t-d-k/LibreCrypt#12]
Hi, Using Windows 10 dev preview, I have installed DoxBox with no issues. Only the explorer program complains about not finding the drivers and suggest rebooting (doesn't solve the issue). 

On a side note, the FAQ mentions that explorer can be used under Wine, however it also complains about not finding drivers and I cannot use DoxBox proper to install the drivers because it doesn't run under Wine.

**Comment by t-d-k** [comment]
Hi, 
Can you please let me know if you have the DLLs on your system - if you look under `C:\Program Files (x86)\DoxBox\`, there should be a folder called 'dll' with files in it like `'FreeOTFE.dll'`
thanks 
tdk

**Comment by conorkickass** [comment]
Hi t-d-k, 

Sorry for the delay. In the wine install. My Wine is set up in a clean wine prefix (though PlayOnLinux), using a 32-bit Windows 7 prefix. 

Also present on the Windows 10 install. (It is just "explorer" that doesn't work in Windows 10). 

Full list: 

./Program Files (x86)/DoxBox/DLL/FreeOTFE.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherAES_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherAES_ltc.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherBlowfish.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherCAST5.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherCAST6_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherDES.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherMARS_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherNull.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherRC6_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherRC6_ltc.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherSerpent_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherTwofish_Gladman.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherTwofish_HifnCS.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherTwofish_ltc.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFECypherXOR.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFEHash_MD.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFEHashMD.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFEHashNull.dll
./Program Files (x86)/DoxBox/DLL/FreeOTFEHashSHA.dll

**Comment by t-d-k** [comment]
Hi,
So to be clear, DoxBox works on Windows 10, but not DoxBoxExplorer, and DoxBoxExplorer doesn't work on Windows 7 under Wine?
The DLLs are installed in the right place. 
Unfortunately I don't have a Windows 10 machine to test it on, but one thing you could try for me is running it in compatibility mode (for Windows XP or Vista).
I'll test with Wine when I get a chance and get back to you.
thanks
tdk

**Comment by conorkickass** [comment]
Hi tdk.

Pretty much correct:

Windows 10: DoxBox (proper) works. Doxbox Explorer complains about no
drivers installed.
Manjaro Linux (Wine pretending to be Windows 7): DoxBox crashes on startup.
Doxbox Explorer complains about no drivers installed.

WIll try compatibility mode and get back to you.

Cheers.

**Comment by t-d-k** [comment]
I have reproduced the bug in Wine, and will look into it after the next release.

**Comment by linux-modder** [comment]
any particular  error code for explorer?
