### ISSUE TITLE
Integration into Windows mount/eject mechanisms

### ISSUE THREAD

**Issue by lusitania** [t-d-k/LibreCrypt#15]
It would be great to have a non-intrusive integration the way LUKS devices are handled in Ubuntu or regular non-encrypted devices in Windows. Especially the "Eject _put device name here_" from "Safely Remove Hardware and Eject Media" in the taskbar and "Eject" in Explorer's context menu would relieve some of the burden introduced by the current UI.

Same goes for mounting devices: Ideally you wouldn't need to click to get the password challenge (again, like it is done in Ubuntu). The next best two improvements are IMO:
- Remember the file system(s) that were previously mounted and immediately select the appropriate tab on "Open partition Box".
- Stop displaying the mount confirmation dialog.

**Comment by t-d-k** [comment]
These are all good ideas, the 'Eject device' menu item is already there if you mount the volume as 'removable', and this will be the default in the next release.

**Comment by linux-modder** [comment]
@lusitania  are you more concerned with convenience or security as the way ubuntu does it is NOT secure nor best practice, although it IS super convienent..
