### ISSUE TITLE
DoxBox won't open GPT LUKS1 partition

### ISSUE THREAD

**Issue by jcnengel** [t-d-k/LibreCrypt#18]
Trying to open a LUKS-encrypted partition (GPT table) using DoxBox fails because DoxBox claims *Unable to open Box. Please check your keyphrase and settings, and try again.*
Testing with the luks.box from the test data everything works perfect.
LUKS dump of my partition shows
>LUKS Dump
>=========
>
>Dump Created By
>---------------
>Platform              : PC
>Application version   : v6.00.00.0000
>Driver ID             : v5.00.0000
>
>
>cryptsetup Style Dump
>---------------------
>LUKS header information for \Device\Harddisk0\Partition8
>
>Version:        1
>Cipher name:    aes
>Cipher mode:    xts-plain64
>Hash spec:      sha1
>Payload offset: 4096
>MK bits:        256
>MK digest:      b5 ad ec 33 6d d1 e4 7b f4 be 9e 4b a4 63 1f 45 5a 8b 81 ad 
>MK salt:        85 56 b6 94 57 e0 d0 d5 44 0d b5 70 c0 88 cc 0f 
>                24 23 14 70 bb d2 a3 3b 75 ea ee 6b 26 0d 4a 12 
>MK iterations:  100375
>UUID:           cf2eb839-e1c1-4a4c-897b-574828b6ca85
>
>Key Slot 0: ENABLED
>        Iterations:             400000
>        Salt:                   39 50 c0 74 5d 0c 0a 3a 8b 54 fc 28 4a a1 bf 05 
>                                d8 d7 b4 9c 1c e8 fe db 3e f6 81 b6 16 72 88 ad 
>        Key material offset:    8
>        AF stripes:             4000
>Key Slot 1: DISABLED
>Key Slot 2: DISABLED
>Key Slot 3: DISABLED
>Key Slot 4: DISABLED
>Key Slot 5: DISABLED
>Key Slot 6: DISABLED
>Key Slot 7: DISABLED
>
>
>Mapped FreeOTFE Drivers
>-----------------------
>Hash pretty title         : SHA-1 (160/512)
>Hash driver KM name       : \Device\FreeOTFE\Hash\{00000000-0000-0000-0000-0000000D0001}
>Hash GUID                 : {00000000-0000-0000-0000-0000000D0002}
>Cypher pretty title       : AES (XTS; 128/128)
>Cypher driver KM name     : \Device\FreeOTFE\Cypher\{00000000-0000-0000-0000-000000010001}
>Cypher GUID               : {00000000-0000-0000-0000-000000010202}
>Sector IV generation      : 32 bit sector ID
>
>
>Master Key
>----------
>User supplied password   : funnypassword
>No master key could be recovered with the specified password.
Needless to say that the password works as a charm under Linux. ;)

**Comment by t-d-k** [comment]
HI, could you try running as administrator and see if that works. Could you also let me know how large the partition is. 
Thanks

**Comment by jcnengel** [comment]
The partition has 15G, running as administrator does not change anything unfortunately.

**Comment by t-d-k** [comment]
Well, it's puzzling. I can open an MBR partition with similar settings with no problem.
Things to double check are that the password does not include any non ASCII characters ('funnypassword' is OK) and you are not pressing 'return' after the password.
Does the partition chooser show the partitions OK? it should look like this:
![partitionselect_fullinfo_new](https://cloud.githubusercontent.com/assets/7935302/7140906/127dd4fc-e2c6-11e4-9249-461e60f6148c.png)
i.e. with 'Linux' as the partition type.
I haven't tested with GPT, I'll update you after I've done that.

**Comment by jcnengel** [comment]
This is a disk with a GPT partition table, therefore the partition selector does not show the same level of information as in your picture here:
![partitionselectorgpt](https://cloud.githubusercontent.com/assets/6266352/7153449/1b40ac50-e34c-11e4-888d-5c5e648842ae.png)

**Comment by t-d-k** [comment]
OK, if run as administrator it should show more information - so it looks like a GPT problem. I'll try to reproduce it and get back to you.

**Comment by jcnengel** [comment]
Unfortunately this is the screenshot from an Administrator instance...

**Comment by disfasia** [comment]
I have the same problem. Partitions without informations, and DoxBox is unable to mount a LUKS partition create with Ubuntu and cryptsetup. I also have to say this happens only on the same physical hard drive on where Windows is running, while trying to mount an external hard drive, formatted in the same way (LUKS on Ubuntu), works. It only gives a BSoD trying to unmount it

**Comment by t-d-k** [comment]
@disfasia Is this with a GPT disk, and when running as administrator? The BSoD issue is known about and only applies if it is mounted as a 'fixed disk' and force unmounted. Version 6.1 mounts drives as 'removable' by default.

**Comment by disfasia** [comment]
@t-d-k yes, running as administrator of course. I can also tell you that if i plug the external HDD, it is seen correctly, with full details of size and paritions, while the HDD where the OS is running is seen with less details. Tell me if you need some tests, I'd be glad to help

**Comment by t-d-k** [comment]
@disfasia This is probably the GPT issue @jcnengel reported.
Later versions of Windows format as GPT by default.
Could you please confirm the disc it doesn't work with is GPT, and the one it does is MBR?
To check this:
* Go to Control Panel > Administrative Tools > Computer Management, and click Disk Management
* On the left of the right lower pane,
   + right-click where it says 'Disk 0' (your OS disc) and select Properties.
   + Select the Volumes tab.
   + The 'Partition style' entry will say either "Master Boot Record (MBR)" or "GUID Partition Table". 

Then repeat for your external disc.

thanks,
tdk

**Comment by disfasia** [comment]
@t-d-k 
- Internal HDD, where the OS is, I can't see proper partitions info and unable to mount: GPT 
- External HDD, I can see partitions info and it is mounting: MBR

**Comment by t-d-k** [comment]
OK, so this is certainly the GPT issue. It looks like there is a problem opening GPT partitions. I'll look into it as soon as I can.

**Comment by erdii** [comment]
I'm not a good programmer, but how can i help you fix this Issue? I really need to be able to open GTP partitions!

**Comment by t-d-k** [comment]
Do you have Visual Studio and can you write C? 
I am making this a priority.

**Comment by erdii** [comment]
I have Visual Studio 2013 installed, but I would install whichever version you are using for development.
Since now i wrote only small C programs for teaching it to myself, but i think i could figure it out. =)

**Comment by t-d-k** [comment]
I'll put up a new release with the improvements I've made so far to GPT handling shortly. 
I've tested creating and opening FreeOTFE volumes on GPT partitions, but not opening LUKS partitions on GPT discs. It would be good if you could test this.

**Comment by erdii** [comment]
That's great to hear!! Yes i will test it. Thanks dude!!

**Comment by t-d-k** [comment]
I have tested with GPT, both LUKS and FreeOTFE volumes and it seems to work OK, so I'll mark this as closed. If you still have issues @erdii , @disfasia or @jcnengel, please reopen.

**Comment by erdii** [comment]
It still doesn't work =(
It tells me that my volume has been mounted , but in Windows Explorer the Volume has 0 bytes in size.

This is what i see in the Open LUKS partition dialog ( the partition with 930,79 GB is my LUKS one)
![mount_luks_dialog](https://cloud.githubusercontent.com/assets/5539202/7770222/5c3c97c0-008c-11e5-976e-3a2f8a8bd426.PNG)

This are the LibreCrypt Container Properties after 'mounting':
![mounted_details](https://cloud.githubusercontent.com/assets/5539202/7770989/2909a1f6-0094-11e5-9fbd-94211ab258f1.PNG)

And this is the end of the cryptsetup-Style dump:

Master Key
----------
> User supplied password   : [omitted]
> Password unlocks key slot: 0
> Recovered master key     :
> 00000000 | 3F 3F 3F 3F 3F 3F 3F 3F | ????????
> 00000008 | 3F 3F 3F 3F 3F 3F 3F 3F | ????????
> 00000010 | 3F 3F 3F 3F 3F 3F 3F 3F | ????????
> 00000018 | 3F 3F 3F 3F 3F B2 3F 3F | ?????.??
> 00000020 | 00 00 00 00 00 00 00 00 | ........
> 00000028 | 00 00 00 00 00 00 00 00 | ........
> 00000030 | 00 00 00 00 00 00 00 00 | ........
> 00000038 | 00 00 00 00 00 00 00 00 | ........

unfortunately this is not my luks master key :/

**Comment by jcnengel** [comment]
Works for me, thanks a lot!
