### ISSUE TITLE
Reviewing update 6.01

### ISSUE THREAD

**Issue by Ralkniv** [t-d-k/LibreCrypt#20]
Well done with the new color interface and all the changes and bug fixes made! It's good to see this great prog alive and kicking...:-)
Here are also some observations and tips for further improvement:

- link to an update from the update check loads a Page Not Found  error 404 (http://doxbox.squte.com/download.html); the download link has to be searched on the web manually
- installer speaks about v6.1 but the About box and update check about v6.01. So which version is it after all?
- minimize on start (autostart) still doesn't work; suggest to look at the workaround which was used in the latest release of FOTFE, there it worked perfectly
- pls add an option to silently check for the new version on each program's start. Many users would welcome this
- clicking on the drive letter of an opened box in the program's main window doesn't load the Explorer and returns an error (before it did load it OK)
- when opening a Box and loading the Key Dialog, pls do focus the cursor by default inside the Keyphrase memo box to easily continue with typing without having to click there beforehand. Do the same also to the first Keyprase memo box of the new Box creation wizard and allow it to jump to the second (Confirm Keyphrase) memo box on pressing Tab key on the keyboard (currently the focus/cursor quite illogically jumps to Back button)
- after autoformatting the new Box and clicking OK on finished format have the Format Removable Disk window closed automatically
- DoxBox Explorer still has an update problem: it shows "This version" as v6.01 BETA 9, suggesting to download "Latest version" v6.01, but on download and install the update check returns still the same result...

**Comment by t-d-k** [comment]
Thanks for this full review, its very helpful.
The next version (6.1.1) will just have the name change to 'LibreCrypt' and any easy bug fixes. The sooner the name is changed the less confusion in the long run. So most of these issues won't be fixed till version 6.2. 

* I'll fix the 404 issue in the next release 6.1.1
* The number is 6.1 - it is formatted wrongly in the about box, should be fixed for 6.1.1.
* The minimize on start issue: I haven't attempted to fixed it yet - this is likely to come in version 6.2. See https://github.com/t-d-k/doxbox/issues/16
* Check for updates on start  - good idea, again likely in version 6.2
* Opening explorer - yes, I can confirm this - should be fixed in 6.1.1
* Issues with password boxes - these should be fixed in 6.1.1
* Closing format dialog: this is a good idea. It's a Windows dialog, not a DoxBox one, so it's not trivial, but I'll look into it.
* Update check - I can confirm this in DoxBox Explorer only. It'll be fixed for 6.1.1.

cheers
tdk

**Comment by Ralkniv** [comment]
Hi TDK,

Looking forward to v 6.1.1.:-) BTW, on renaming the program to LibreCrypt,
how are you going to rename the "boxes" as well as the used extension? I
think the original name file/folder container was a suitable one and "box"
was a rather unfortunate as it terminologically collided with memo boxes,
etc. Here, return to name "volume" as well as extension .vol could be a
worthwhile option to consider.

Being an occasional and amateur Delphi programmer, may I suggest a possible
workaround how to automatically close the Windows format dialog box -
searching for its caption name and force-closing app/applet that has it.
This can be done quite easily, though this would not work with other
language versions of Windows; well, those users would still have to click
on the Close button... So what...:-)

When do you expect to release the next update?

Thanks for good job and best regards:-),
David Vinklar (nick Ralkniv, being Vinklar read from back...)

**Comment by t-d-k** [comment]
Yes the 'boxes' will be renamed to 'containers'. I don't know about the extension yet, any suggestions?
Yes, the dialog box can be closed with a windows message, but this kind of thing is messy.

**Comment by Ralkniv** [comment]
I'd stick to original - .vol (=volume). I didn't really like the .box...:-)

**Comment by Ralkniv** [comment]
Removing Close. I clicked on this by mistake...

**Comment by Ralkniv** [comment]
There is also one other bug that I noticed. When running DoxBox from a read-only medium (e.g., CD/DVD-ROM) an error box is invoked on the program's launch informing that the INI file is read-only and the settings cannot be saved. I would understand such a behavior if I attempted to change a setting, but I did not attempt to change any, knowing that it's all read-only. I also used "/readonly" command line parameter. And as if this was not enough, the same error box fires once more - also when closing DoxBox from the read-only location. All this is unnecessary. The error box should fire only if changes are to be made, NOT if none are made.

**Comment by t-d-k** [comment]
Thanks for this. The program saves a value to the INI file to say it is running, this is used to detect crashes, which is why you get the error message on every launch. 
It will be fixed in the next release.

**Comment by t-d-k** [comment]
All these issues should be fixed in 6.2 Beta, except the format dialog.

**Comment by linux-modder** [comment]
Given 6.2 is out closing this ticket.
