### ISSUE TITLE
Updating  the ciphers ?  

### ISSUE THREAD

**Issue by linux-modder** [t-d-k/LibreCrypt#23]
Looking back through the linux scripts and  being a daily and avid luks user those  ciphers are  often no longer  consider worth a damn... have forked and planning to  start  a update for the dependencies and such but lack of  user defined  functions and options is also less then optimal..

**Comment by t-d-k** [comment]
Yes, my bash-fu is less than ideal.
By all means rewrite the Linux script. The main thing is that it should be compatible with hidden volumes accessed using LibreCrypt, which means the offset calculation shouldn't change.

**Comment by linux-modder** [comment]
@t-d-k , been busy this week but taking a deeper look as the  recent  luks issues are VERY reproducable and  nearly make it useless for linux atm

**Comment by linux-modder** [comment]
Merging with issue regarding LUKSerror

**Comment by t-d-k** [comment]
@linux-modder  
You can reproduce the other issues?
Does the fact you have closed this issue mean you won't be doing this now?
