### ISSUE TITLE
Getting rid of "Test Mode Windows 7 Build xxxx"

### ISSUE THREAD

**Issue by jwhendy** [t-d-k/LibreCrypt#25]
Greetings,

I'm following along with the documentation, or trying to, on this site. It's a bit confusing since some of your links point to the DoxBox site. In any case, both links regarding removing the Test Build text from my desktop are broken. There's one here (under "Automatic Installation"):

- Link: https://github.com/t-d-k/LibreCrypt/blob/master/docs/installation_and_upgrading__PC.md
- Points here (404): https://github.com/t-d-k/LibreCrypt/blob/master/docs/impact_of_kernel_driver_signing.html

There's another here on DoxBox (also in the "Automatic Installation" section):
- Link: http://doxbox.squte.com/doxbox/installation_and_upgrading__PC.html
- Points here (404): http://doxbox.squte.com/doxbox/impact_of_kernel_driver_signing.html

Can you provide the correct link or these instructions and update the docs?

**Comment by jwhendy** [comment]
It appears this is just a `.md` vs. `.html` thing. Maybe there's another version of the docs hosted outside of github that uses `.html`? Somehow I stumbled on the actual page (I think I just googled "remove test mode windows 7 build librecrypt" and got a hit), which is:

- https://github.com/t-d-k/LibreCrypt/blob/master/docs/impact_of_kernel_driver_signing.md

**Comment by t-d-k** [comment]
Thanks for reporting this.
You are correct, there is an html version [here](http://squte.com/doxbox/installation_and_upgrading__PC.html).
The markdown version is the master, so should have links to `.md` files. There are lots of other broken links as well, which I'll fix ASAP, meanwhile if you get a 404, you can change the `.html` extension to `.md`

**Comment by linux-modder** [comment]
I'll take  a deeper look into the lvm itself  today and tomorrow then
thanks...

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
--------------------------------------------------------------------------------------------------
pub  3072D/718BF597
<http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597> 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597
uid     Corey Sheldon (Fedora Key) <sheldon.corey@gmail.com>
---------------------------------------------------------------------------------------------------
