### ISSUE TITLE
Force dm-crypt checkbox in "Open partition..."

### ISSUE THREAD

**Issue by mmatuska** [t-d-k/LibreCrypt#28]
A "force dm-crypt" checkbox in "Open partition..." dialog would give a workaround the problem of not opening LUKS partitions on Windows 7 and 8.

Related to #24

**Comment by t-d-k** [comment]
These are comments by @mmatuska on this point on a different issue:

> I am having the same issue on Windows 7 Pro 64 bit PC
> I am also not able to dump luks.box or the partition:
> "Unable to dump out critical data block. ..."

> I have some more information on this:

> If you open luks.box via "File->Linux Container->Mount file (dm-crypt)" a different key entry box appears ("Librecrypt dm-crypt key entry") and the mount is successful.

> If you do the same via "Open file..." or "Open partition..." (for a partition) the "Key Phrase For LUKS Container" entry box appears and the mount does not work ("Unable to open container. Please check your keyphrase and settings, and try again.")

**Comment by t-d-k** [comment]
When you say it was 'successful' - could you browse the drive after it was opened, and see a file called 'readme.txt'? If you get a prompt to format the drive in windows, and accept it, then this will corrupt the volume and it won't afterwards open as a LUKs file.

I have found a relevant bug, namely that a LUKS volume will only open if it is writeable, even if opening read-only. This is fixed for the next release.
Could you please retest with LUKS.box, after redownloading the file, and setting the file to writeable?
thanks
tdk

**Comment by t-d-k** [comment]
The menu items and dialogs are being reworked in 6.3 to make it clear whether a volume is being opened as a dm-crypt one or LUKS, which should clear some of this confusion.
