### ISSUE TITLE
Can't get rid of "Test mode" on Windows 7 (LC is installed, not portable)

### ISSUE THREAD

**Issue by alex3kov** [t-d-k/LibreCrypt#32]
After reading documentation on main page I thought Test mode only applied to running LC in portable mode, so I installed it properly. "Test mode" label is in the right bottom corner of the desktop. Mounting partitions works OK though.
I tried to allow test-signed drivers -> reboot -> disallow test-signed drivers -> reboot - that leaves me with no "Test mode" label on desktop, but LC is not working, saying it cannot load drivers.
Windows 7 SP1 64

**Comment by t-d-k** [comment]
Test mode is necessary for running LC in both portable mode and installed. It is not necessary for LC Explorer.
The "disallow test-signed drivers" option is behaving as expected.
To run LC in portable or installed mode you will need to allow test signed drivers and reboot again.
To hide the "Test mode" text, follow the instructions here: https://github.com/t-d-k/LibreCrypt/blob/master/docs/impact_of_kernel_driver_signing.md#method-3-testsigning-on-instructions
