### ISSUE TITLE
unable to open container after forcefully closing it

### ISSUE THREAD

**Issue by endercollins** [t-d-k/LibreCrypt#33]
Hi, 
I have a problem when trying to open a container created within a container with Doxbox after forcefully closing it. Now it just gives me an error message and doesn't open. I use Librecrypt 6.2 on Windows 64x. Could someone please tell me if there is any way to recover the files within? I am a newbie so I am not good at this.
Thank you

**Comment by t-d-k** [comment]
Force closing a container can leave the filesystem corrupt. If possible close containers normally.
Using hidden containers will also give errors if the offset is not identical, or if the outer container is written to after creating the hidden container.
