### ISSUE TITLE
Donation outside UK?

### ISSUE THREAD

**Issue by hholst80** [t-d-k/LibreCrypt#47]
It seems the donation button on the main page leads to a Paypal page as it should. But I can only select England and GBP currency. The button in the "donate.md" page works as expected.

EDIT: My bad. It's the address line that only shows UK addresses.

![image](https://cloud.githubusercontent.com/assets/6200749/14386322/83631124-fda4-11e5-97b7-29e1b612c15d.png)

**Comment by hholst80** [comment]
The issue above aside, I managed to send 10 GBP your way.

**Comment by t-d-k** [comment]
Thank you! I take it this isn't an issue?

**Comment by ssdnvv** [comment]
No, thats no issue.
I sent another 10GBP, too - a while ago.
Just to ensure you got some motivation to keep gooing - its been quite a long time since your last activities on this project. No criticism, but some people thought this project might be dead (and maybe you too, just as Sarah Dean...).

**Comment by t-d-k** [comment]
Thank you very much for your donations. Sadly, I've been busy with work. 
Have you opened a bug report for the issue mounting a partition?
