### ISSUE TITLE
Librecrypt CLI Windows Admin Error

### ISSUE THREAD

**Issue by gill984** [t-d-k/LibreCrypt#53]
Currently I am attempting to use the Librecrypt CLI to send a command to mount some LUKS partitions via a script. The command I am sending is:
"LibreCrypt.exe /mount /volume \\.\PhysicalDrive1\Partition1 /linux /password password"

Doing this brings up an error message that I need to be an administrator to run this command, even though I already am one.

I know I am running as an admin because I start CMD as an administrator (right click, run as administrator). I've also done some other simple tests to make sure I am an admin. I can open the Librecrypt GUI as an admin to open my partition with no errors, but the CLI complains that I need to be an administrator. I can actually run some commands using the CLI, for example I believe I ran the "/count" command just fine.

Any help would be appreciated, thank you.

**Comment by t-d-k** [comment]
I can confirm this is a bug. It's fixed in the next release of LC. You'll have to give the device in the form: `\Device\Harddisk1\Partition1` and use the `/silent` switch to avoid a dialog showing.

**Comment by gill984** [comment]
Thank you very much!

Is this fixed in any of the currently available versions of LibreCrypt? Can I find the commit for this fix anywhere?

Thanks again!

**Comment by t-d-k** [comment]
No, it will be in the next release of LC. I'm going to put some logging in that, so maybe wait for the one after that.
