### ISSUE TITLE
drag-and-drop to enter the password to the edit box is not enabled

### ISSUE THREAD

**Issue by t-d-k** [t-d-k/LibreCrypt#54]
reported by @Ralkniv :
 
pls make sure before releasing upgrade that drag-and-drop to enter the password to the edit box is enabled as it is not the case in the latest (6.2.5806.4070) EXE build. It would be a pity and the prog would be prone to easy key-logging and clipboard-logging schemes. A small detail that makes a huge difference allowing to safely drag passwords from KeePass or HashPass... This is what differentiated FOTFE from TrueCrypt, Dekart Private Disk, SafeHouse and many others, and this was one of the valid reasons of preference for many...

**Comment by Ralkniv** [comment]
This was reported by me originally already on February 7, 2016, as **LibreCrypt 6.2.5806.40706 - security issue**, without anyone's reacton... I regard this feature to be of utmost importance.

**Comment by t-d-k** [comment]
Sorry. I missed that.
