### ISSUE TITLE
[Feature Request] Parity / Data Redundancy

### ISSUE THREAD

**Issue by izomiac** [t-d-k/LibreCrypt#56]
While this is somewhat complex, one useful feature for containers would be to reserve a small percentage of the filesize for redundancy, similar to what RAID6 or Parchives do.  

The main benefit would be with storing records in a confidential manner for long periods of time.  The encryption keeps them secure, and the parity keeps them intact/recoverable against bit rot.  By implementing it with OTFE, it becomes much less tedious than creating Parchives (or similar) for each file on the container or for the container itself.  Containers are also frequently large files, so they're more prone to corruption during storage or transfer.

**Comment by t-d-k** [comment]
This is something better done in a separate tool, which could be used in conjunction with LibreCrypt if needed.
