### ISSUE TITLE
can't open partition, unless run as administrator

### ISSUE THREAD

**Issue by t-d-k** [t-d-k/LibreCrypt#7]
reported by comicfans:
*****************************************************************************************************************

seems that doxbox can not read luks partition, luks dump just failed (but freeotfe works)

doxbox output 
LUKS Dump
=========

Dump Created By
---------------
Platform              : PC
Application version   : v6.00.00.0000
Driver ID             : v5.00.0000
ERROR: Unable to read LUKS header?!

freeotfe output

LUKS Dump
=========

Dump Created By
---------------
Platform              : PC
Application version   : v5.21.00.4058
Driver ID             : v5.00.0000

cryptsetup Style Dump
---------------------
LUKS header information for \Device\Harddisk0\Partition6

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha1
Payload offset: 4096
MK bits:        512
MK digest:      1d 19 ff f1 5a cd 98 a1 f1 db 17 0b cc 1a 78 b4 bc 6c 6c 1c 
MK salt:        75 5f fc ea 01 6a 36 b2 0c 7a 5c 65 df 6b a5 ea 
                9a b2 c1 af d1 02 53 06 70 37 d5 df 14 60 24 c1 
MK iterations:  79125
UUID:           6ef4d308-4ff7-46c9-81ff-074993e80f53

Key Slot 0: ENABLED
        Iterations:             308805
        Salt:                   c6 da 2c e2 c1 5a 9a 43 e7 8e 52 9e fe 3d b2 82 
                                69 c1 8d 2b 41 f6 ae 1f 09 03 8c cd d9 fd 71 ec 
        Key material offset:    8
        AF stripes:             4000
Key Slot 1: DISABLED
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED

Mapped FreeOTFE Drivers
-----------------------
Hash pretty title         : SHA-1 (160/512)
Hash driver KM name       : \Device\FreeOTFE\Hash\{00000000-0000-0000-0000-0000000D0001}
Hash GUID                 : {00000000-0000-0000-0000-0000000D0002}
Cypher pretty title       : AES (XTS; 256/128)
Cypher driver KM name     : \Device\FreeOTFE\Cypher\{00000000-0000-0000-0000-000000010001}
Cypher GUID               : {00000000-0000-0000-0000-000000010204}
Sector IV generation      : 32 bit sector ID

Master Key
----------
User supplied password   : 
No master key could be recovered with the specified password.

*****************************************************************************************************************

**Comment by orion1024** [comment]
I have this issue as well. Once I stopped trying to use DoxBox Explorer, I stumbled on this one when opening my LUKS partition.
I remember it used to work though on my first LUKS partition. It was much smaller in size (1 or 2 GB at most) and the new one is 70+ GB.

Let me know if you need me to run some tests.

**Comment by t-d-k** [comment]
Hi comicfans:
The error you are getting suggests some kind of permissions error reading the partition.
Could you try again, running as administrator. To do this right-click the executable and choose 'run as administrator', and let me know what the result is.
Could you also let me know the size of the partition, and the Operating System you are using.
Thanks
tdk

**Comment by t-d-k** [comment]
Hi orion1024: 
Thanks for reporting this.
Could you let me know what the error you get when trying to open it is? Also could you please post the output of the 'Dump LUKS details' command. This is under the 'File->Linux Volume' menu.
Cheers
tdk

**Comment by orion1024** [comment]
@t-d-k 

Actually it was just that I didn't run DoxBox as administrator. I was sure I was doing that the first time, but apparently not.
It's opening just fine now,  thanks for the help still

**Comment by t-d-k** [comment]
I haven't heard back from @comicfans - so I'll assume this was the same as with @orion1024 - not running as administrator.

**Comment by t-d-k** [comment]
Not being able to open a partition unless run as admin is a bug, it should UAC escalate.

**Comment by t-d-k** [comment]
This is fixed in 6.2
